export const projectList = [
  {
    title: 'MapleStory Worlds',
    company: 'Nexon',
    period: '2022.05 ~',
    image: '/assets/img/project/maplestoryworlds.svg',
    description: '메이플스토리 월드는 누구나 자유롭게 게임 콘텐츠를 제작하고 플레이하는 플랫폼입니다.',
    part: ['페이지 개발 및 UI/UX 개선'],
    link: [
      { text: '소개영상', href: 'https://www.youtube.com/watch?v=uGvyjhemEVA' },
      { text: '홈페이지', href: 'https://maplestoryworlds.nexon.com' },
    ],
    techList: [
      { icon: 'html', tooltip: 'HTML5' },
      { icon: 'css', tooltip: 'CSS3' },
      { icon: 'javascript', tooltip: 'Javascript' },
      { icon: 'vue', tooltip: 'Vue' },
      { icon: 'nuxt', tooltip: 'Nuxt' },
      { icon: 'webpack', tooltip: 'Webpack' },
      { icon: 'babel', tooltip: 'Babel' },
      { icon: 'eslint', tooltip: 'Eslint' },
      { icon: 'prettier', tooltip: 'Prettier' },
    ],
  },
  {
    title: 'LawShot',
    company: 'HumaxIT',
    period: '2019.05 ~ 2022.04',
    image: '/assets/img/project/lawshot.svg',
    description: '법무법인의 업무를 시스템화하여 업무의 효율성을 높이기 위한 서비스입니다.',
    part: [
      '페이지 개발 및 UI/UX 개선',
      '공통 컴포넌트 개발',
      '메일 회신 이력 서비스 개발 및 유지보수',
      'ERD 설계 및 Node Server API 구현',
      '변호사 인터뷰, 법무법인 파견 등을 통한 요구사항 파악',
    ],
    link: [
      { text: '소개영상', href: 'https://www.youtube.com/watch?v=Is9ck9m9ys4' },
      { text: '홈페이지', href: 'https://home.lawshot.co.kr' },
      { text: '서비스', href: 'https://live.lawshot.co.kr' },
    ],
    techList: [
      { icon: 'html', tooltip: 'HTML5' },
      { icon: 'css', tooltip: 'CSS3' },
      { icon: 'javascript', tooltip: 'Javascript' },
      { icon: 'node', tooltip: 'Node' },
      { icon: 'react', tooltip: 'React' },
      { icon: 'redux', tooltip: 'Redux' },
      { icon: 'redux-saga', tooltip: 'Redux Saga' },
      { icon: 'webpack', tooltip: 'Webpack' },
      { icon: 'babel', tooltip: 'Babel' },
      { icon: 'eslint', tooltip: 'Eslint' },
      { icon: 'prettier', tooltip: 'Prettier' },
    ],
  },
];
