export const projectList = [
  {
    title: 'MapleStory Worlds',
    company: 'Nexon',
    period: '2022.05 ~',
    image: '/portfolio/assets/img/project/maplestoryworlds.svg',
    description: '메이플스토리 월드는 누구나 자유롭게 게임 콘텐츠를 제작하고 플레이하는 플랫폼입니다.',
    part: ['페이지 개발 및 UI/UX 개선', 'Youtube API를 이용한 쇼츠(뭐 할까?) 개발', '공통 컴포넌트 개발 및 유지보수'],
    link: [
      { text: '유투브 채널', href: 'https://www.youtube.com/@MapleStoryWorlds' },
      { text: '소개영상', href: 'https://www.youtube.com/watch?v=uGvyjhemEVA' },
      { text: '홈페이지', href: 'https://maplestoryworlds.nexon.com' },
    ],
    techList: [
      { icon: 'html', tooltip: 'HTML5' },
      { icon: 'css', tooltip: 'CSS3' },
      { icon: 'javascript', tooltip: 'Javascript' },
      { icon: 'vue', tooltip: 'Vue' },
      { icon: 'nuxt', tooltip: 'Nuxt' },
    ],
  },
  {
    title: 'FACEPLAY',
    company: 'Nexon',
    period: '2022.12 ~ 2023.07',
    image: '/portfolio/assets/img/project/faceplay.svg',
    description:
      '화상 카메라를 이용해 멀리 떨어진 사람들과 쉽고 빠르게 파티 게임을 즐길 수 있는 종합 놀이 플랫폼입니다.',
    part: [
      '페이지 개발 및 UI/UX 개선',
      'Youtube API 이용한 영상 플레이 기능 개발',
      'Sendbird SDK을 이용한 채팅 기능 유지보수',
      'Social(팔로잉, 팔로워) 기능 개발',
      '공통 컴포넌트 개발 및 유지보수',
    ],
    link: [
      { text: '유투브 채널', href: 'https://www.youtube.com/@FACEPLAY_nexon' },
      { text: '소개영상', href: 'https://www.youtube.com/watch?v=U4oReQjhov0' },
      { text: '홈페이지', href: 'https://faceplay.nexon.com/' },
    ],
    techList: [
      { icon: 'html', tooltip: 'HTML5' },
      { icon: 'css', tooltip: 'CSS3' },
      { icon: 'javascript', tooltip: 'Javascript' },
      { icon: 'react', tooltip: 'React' },
      { icon: 'react-query', tooltip: 'React Query' },
      { icon: 'next', tooltip: 'Next' },
    ],
    disabled: true,
  },
  {
    title: 'LawShot',
    company: 'HumaxIT',
    period: '2019.05 ~ 2022.04',
    image: '/portfolio/assets/img/project/lawshot.svg',
    description: '법무법인의 업무를 시스템화하여 업무의 효율성을 높이기 위한 서비스입니다.',
    part: [
      '페이지 개발 및 UI/UX 개선',
      '공통 컴포넌트 개발 및 유지보수',
      '메일 회신 이력 서비스 개발 및 유지보수',
      'ERD 설계 및 Node Server API 구현',
      '변호사 인터뷰, 법무법인 파견 등을 통한 요구사항 파악',
    ],
    link: [
      { text: '소개영상', href: 'https://www.youtube.com/watch?v=Is9ck9m9ys4' },
      { text: '홈페이지', href: 'https://home.lawshot.co.kr' },
      { text: '서비스', href: 'https://live.lawshot.co.kr' },
    ],
    techList: [
      { icon: 'html', tooltip: 'HTML5' },
      { icon: 'css', tooltip: 'CSS3' },
      { icon: 'javascript', tooltip: 'Javascript' },
      { icon: 'node', tooltip: 'Node' },
      { icon: 'react', tooltip: 'React' },
      { icon: 'redux', tooltip: 'Redux' },
      { icon: 'redux-saga', tooltip: 'Redux Saga' },
    ],
  },
];
