export const techList = [
  { icon: 'html', tooltip: 'HTML5' },
  { icon: 'css', tooltip: 'CSS3' },
  { icon: 'javascript', tooltip: 'Javascript' },
  { icon: 'typescript', tooltip: 'Typescript' },
  { icon: 'node', tooltip: 'Node' },
  { icon: 'react', tooltip: 'React' },
  { icon: 'redux', tooltip: 'Redux' },
  { icon: 'redux-saga', tooltip: 'Redux Saga' },
  { icon: 'next', tooltip: 'Next' },
  { icon: 'vue', tooltip: 'Vue' },
  { icon: 'nuxt', tooltip: 'Nuxt' },
  { icon: 'webpack', tooltip: 'Webpack' },
  { icon: 'babel', tooltip: 'Babel' },
  { icon: 'eslint', tooltip: 'Eslint' },
  { icon: 'prettier', tooltip: 'Prettier' },
];
